# Generated by Django 3.1.7 on 2021-03-25 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='hash',
        ),
    ]
